# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.12-alpine

# Install build dependencies
RUN apk add --no-cache gcc musl-dev linux-headers git

# Create a working directory
WORKDIR /app

# Copy the requirements and project files
COPY pyproject.toml setup.py ./
COPY src ./src
COPY README.md ./
COPY MANIFEST.in ./
COPY LICENSE ./
COPY CHANGELOG.md ./
COPY docs ./docs

# Install pip dependencies and build the package
RUN pip install --upgrade pip && \
    pip install --ignore-installed --no-cache-dir build && \
    python -m build && \
    pip install --no-cache-dir .

# Expose logs directory if necessary
VOLUME ["/app/.practices"]

# Set the default command to run the MCP server
ENTRYPOINT ["practices-server"]
